name: "↩️ Regression"
description: Report functionality that used to work but is now broken
labels: ["Regression", "Needs Approval"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a regression! Please help us understand what changed.

  - type: input
    id: last_working
    attributes:
      label: Last Working Version
      description: What was the last version where this worked correctly?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: broken_version
    attributes:
      label: First Broken Version
      description: What version introduced the regression?
      placeholder: "e.g., 1.1.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What Changed?
      description: Describe what used to work and what's now broken
      placeholder: |
        Previously: The feature worked like X
        Now: The feature does Y instead
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this regression?
    validations:
      required: true 