name: "🔒 Security Issue"
description: Report a security vulnerability (private by default)
labels: ["Security", "Needs Approval"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a critical security vulnerability, please report it directly to security@koroflow.com instead of creating a public issue.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this security issue?
      options:
        - "🟢 Low: Minor vulnerability"
        - "🟡 Medium: Limited impact"
        - "🔴 High: Significant risk"
        - "⚫ Critical: Immediate action required"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: "A detailed explanation of the security issue..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What's the potential impact of this vulnerability?
      placeholder: "What could an attacker do if they exploited this?"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this security issue?
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have any suggestions for fixing this?
    validations:
      required: false 