name: Auto Link Issue
on:
  pull_request:
    types: [opened, edited]

jobs:
  auto-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Link Issue
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const match = pr.title.match(/kf-(\d+)/);
            
            if (match) {
              const issueNumber = match[1];
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `Linked to #${issueNumber}`
              });
              
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: ['has-pr']
              });
            }
