name: Renovate
on:
  schedule:
    - cron: "0 3 * * 1"  # Runs at 3 AM UTC every Monday
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }} 